name: tugaspert4_mp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
    
  # Package Navigasi & Peta Pertemuan 14
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.3
  permission_handler: ^12.0.3
  http: ^1.6.0

  # Package Pendukung Project Sebelumnya
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.10
  simple_alert_dialog: ^1.0.1
  cherry_toast: ^1.13.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.5.5
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true